workspaceLocation: dotfiles-sh/dotfiles-sh.code-workspace

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Cache workspace images
    command: |
      l=/workspace/.dinit;
      touch "$l";
      for img in full min; do
        docker pull axonasif/dotfiles-testing-${img}:latest;
        printf '%s\n' done > "$l";
      done
      exit;

  - name: Compile project
    command: |
      curl --proto '=https' --tlsv1.2 -sSfL "https://git.io/Jc9bH" | bash -s selfinstall; # Install bashbox
      bashbox build --release;
      touch /workspace/.binit;
      gp sync-done compile;

  - name: Open all src/ *.sh files
    command: |
      gp sync-await compile;
      gp ports await 23000 1>/dev/null;
      for file in install.sh src/utils/* src/variables.sh src/main.sh; do {
        gp open "$file";
      } done
      exit;
  - name: Bind mount repos dir
    command: |
      dir="$HOME/.dotfiles/repos";
      target_dir="$PWD/${dir##*/}"
      if test -e "$dir"; then {
        mkdir -p "$target_dir";
        sudo mount --bind "$dir" "$target_dir";
      } fi
      exit 0;
  - name: Live test dotfiles
    command: |
      # DOTFILES_TMUX_NO_TAKEOVER
      gp sync-await compile;
      source "$HOME/.bashbox/env";
      bashbox livetest; # `livetest` is a custom project command defined in `Bashbox.sh`

vscode:
  extensions:
    - mads-hartmann.bash-ide-vscode
    - timonwong.shellcheck

ports:
  - port: 33000
    onOpen: ignore
