additionalRepositories:
  - url: https://github.com/axonasif/dotfiles.public.git
workspaceLocation: dotfiles-sh/dotfiles-sh.code-workspace

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Cache workspace images
    command: |
      l=/workspace/.dinit;
      touch "$l";
      docker pull axonasif/dotfiles-testing:latest;
      printf '%s\n' done > "$l";
      exit;

  - name: Compile project
    command: |
      curl --proto '=https' --tlsv1.2 -sSfL "https://git.io/Jc9bH" | bash -s selfinstall; # Install bashbox
      bashbox build --release;
      touch /workspace/.binit;
      gp sync-done compile;

  - name: Open all src/ *.sh files
    command: |
      gp sync-await compile;
      gp ports await 23000 1>/dev/null;
      for file in install.sh src/utils/* src/variables.sh src/main.sh; do {
        gp open "$file";
      } done
      exit;

  - name: Live test dotfiles
    command: |
      gp sync-await compile;
      source "$HOME/.bashbox/env";
      bashbox live; # `live` is a custom project command defined in `Bashbox.sh`

vscode:
  extensions:
    - mads-hartmann.bash-ide-vscode
    - timonwong.shellcheck

ports:
  - port: 33000
    onOpen: ignore
